-- MySQL Script generated by MySQL Workbench
-- 06/09/17 12:56:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyectosfa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectosfa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectosfa` DEFAULT CHARACTER SET utf8 ;
USE `proyectosfa` ;

-- -----------------------------------------------------
-- Table `proyectosfa`.`serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`serie` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`serie` (
  `idserie` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `serie` VARCHAR(15) NOT NULL,
  `resolucion` VARCHAR(30) NOT NULL,
  `numero_inicial` INT NOT NULL,
  `numero_final` INT NOT NULL,
  `documento_siguiente` INT NOT NULL,
  PRIMARY KEY (`idserie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`cliente` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NULL,
  `nombre` VARCHAR(250) NOT NULL,
  `direccion` VARCHAR(250) NULL,
  `telefono` VARCHAR(50) NULL,
  `nit` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NULL,
  `fecha_creacion` DATE NOT NULL,
  `saldo` DECIMAL(11,2) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`vendedor` (
  `idvendedor` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `correo` VARCHAR(100) NULL,
  `telefono` VARCHAR(50) NULL,
  `fecha_creacion` DATE NULL,
  PRIMARY KEY (`idvendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`nota_credito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`nota_credito` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`nota_credito` (
  `idnota_credito` INT NOT NULL AUTO_INCREMENT,
  `codigo_serie` INT NOT NULL,
  `numero_nota` INT NOT NULL,
  `estado` INT NOT NULL,
  `fecha_documento` DATE NULL,
  `fecha_creacion` DATE NOT NULL,
  `cliente_id` INT NOT NULL,
  `vendedor_id` INT NULL,
  `nota_creditocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idnota_credito`),
  INDEX `fk_serie_nc_idx` (`codigo_serie` ASC),
  INDEX `fk_nc_cliente_idx` (`cliente_id` ASC),
  INDEX `fk_nc_vendedor_idx` (`vendedor_id` ASC),
  CONSTRAINT `fk_nc_serie`
    FOREIGN KEY (`codigo_serie`)
    REFERENCES `proyectosfa`.`serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nc_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `proyectosfa`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nc_vendedor`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `proyectosfa`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`categoria` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  `condicion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`inventario` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`inventario` (
  `id_inventario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NULL,
  `unidad` VARCHAR(20) NOT NULL,
  `estado` INT NULL,
  `idcategoria` INT NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `fk_inve_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_inve_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `proyectosfa`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`almacen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`almacen` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`almacen` (
  `idalmacen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  `ubicacion` VARCHAR(50) NULL,
  PRIMARY KEY (`idalmacen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`nc_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`nc_detalle` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`nc_detalle` (
  `idnc_detalle` INT NOT NULL,
  `id_inv` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  `cantidad` DECIMAL(11,2) NOT NULL,
  `precio` DECIMAL(11,2) NULL,
  `impuesto` DECIMAL(11,2) NULL,
  `subtotal` DECIMAL(11,2) NULL,
  INDEX `fk_ncd_notacredito_idx` (`idnc_detalle` ASC),
  INDEX `fk_ncd_inventario_idx` (`id_inv` ASC),
  INDEX `fk_ncd_almacen_idx` (`id_almacen` ASC),
  CONSTRAINT `fk_ncd_notacredito`
    FOREIGN KEY (`idnc_detalle`)
    REFERENCES `proyectosfa`.`nota_credito` (`idnota_credito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ncd_inventario`
    FOREIGN KEY (`id_inv`)
    REFERENCES `proyectosfa`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ncd_almacen`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `proyectosfa`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`factura` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `codigo_serie` INT NOT NULL,
  `numero_fac` INT NOT NULL,
  `estado` INT NOT NULL,
  `fecha_documento` DATE NULL,
  `fecha_creacion` DATE NULL,
  `cliente_id` INT NOT NULL,
  `vendedor_id` INT NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_fact_serie_idx` (`codigo_serie` ASC),
  INDEX `fk_fact_cliente_idx` (`cliente_id` ASC),
  INDEX `fk_fac_vendedor_idx` (`vendedor_id` ASC),
  CONSTRAINT `fk_fact_serie`
    FOREIGN KEY (`codigo_serie`)
    REFERENCES `proyectosfa`.`serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `proyectosfa`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fac_vendedor`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `proyectosfa`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`fac_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`fac_detalle` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`fac_detalle` (
  `idfac_detalle` INT NOT NULL AUTO_INCREMENT,
  `idfactura` INT NOT NULL,
  `id_inv` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  `cantidad` DECIMAL(11,2) NULL,
  `precio` DECIMAL(11,2) NULL,
  `impuesto` DECIMAL(11,2) NULL,
  `subtotal` DECIMAL(11,2) NULL,
  INDEX `fk_facdetalle_inventario_idx` (`id_inv` ASC),
  INDEX `fk_facdetalle_almacen_idx` (`id_almacen` ASC),
  INDEX `fk_fcdetalle_factura_idx` (`idfactura` ASC),
  PRIMARY KEY (`idfac_detalle`),
  CONSTRAINT `fk_facdetalle_inventario`
    FOREIGN KEY (`id_inv`)
    REFERENCES `proyectosfa`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facdetalle_almacen`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `proyectosfa`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fcdetalle_factura`
    FOREIGN KEY (`idfactura`)
    REFERENCES `proyectosfa`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`producto_almacen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`producto_almacen` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`producto_almacen` (
  `idprodalmacen` INT NOT NULL AUTO_INCREMENT,
  `id_inve` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  `existencia` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idprodalmacen`),
  CONSTRAINT `fk_producto_inventario`
    FOREIGN KEY (`id_inve`)
    REFERENCES `proyectosfa`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_almacen`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `proyectosfa`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`pago_recibido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`pago_recibido` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`pago_recibido` (
  `idpago_recibido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_fcaja` INT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idpago_recibido`),
  INDEX `fk_pr_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_pr_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `proyectosfa`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`pago_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`pago_detalle` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`pago_detalle` (
  `idpago_detalle` INT NOT NULL,
  `id_factura` INT NOT NULL,
  `saldo` DECIMAL(11,2) NULL,
  INDEX `fk_pd_pr_idx` (`idpago_detalle` ASC),
  INDEX `fk_pd_factura_idx` (`id_factura` ASC),
  CONSTRAINT `fk_pd_pr`
    FOREIGN KEY (`idpago_detalle`)
    REFERENCES `proyectosfa`.`pago_recibido` (`idpago_recibido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pd_factura`
    FOREIGN KEY (`id_factura`)
    REFERENCES `proyectosfa`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
