-- MySQL Script generated by MySQL Workbench
-- 10/10/17 12:53:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyectosfa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectosfa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectosfa` DEFAULT CHARACTER SET utf8 ;
USE `proyectosfa` ;

-- -----------------------------------------------------
-- Table `proyectosfa`.`serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`serie` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`serie` (
  `idserie` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `serie` VARCHAR(15) NOT NULL,
  `resolucion` VARCHAR(30) NOT NULL,
  `numero_inicial` INT NOT NULL,
  `numero_final` INT NOT NULL,
  `documento_siguiente` INT NOT NULL,
  PRIMARY KEY (`idserie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`cliente` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NULL,
  `nombre` VARCHAR(250) NOT NULL,
  `direccion` VARCHAR(250) NULL,
  `telefono` VARCHAR(50) NULL,
  `nit` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NULL,
  `fecha_creacion` DATE NOT NULL,
  `saldo` DECIMAL(11,2) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`vendedor` (
  `idvendedor` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `correo` VARCHAR(100) NULL,
  `telefono` VARCHAR(50) NULL,
  `fecha_creacion` DATE NULL,
  PRIMARY KEY (`idvendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`nota_credito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`nota_credito` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`nota_credito` (
  `idnota_credito` INT NOT NULL AUTO_INCREMENT,
  `codigo_serie` INT NOT NULL,
  `numero_nota` INT NOT NULL,
  `estado` INT NOT NULL,
  `fecha_documento` DATE NULL,
  `fecha_creacion` DATE NOT NULL,
  `cliente_id` INT NOT NULL,
  `vendedor_id` INT NULL,
  `nota_creditocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idnota_credito`),
  INDEX `fk_serie_nc_idx` (`codigo_serie` ASC),
  INDEX `fk_nc_cliente_idx` (`cliente_id` ASC),
  INDEX `fk_nc_vendedor_idx` (`vendedor_id` ASC),
  CONSTRAINT `fk_nc_serie`
    FOREIGN KEY (`codigo_serie`)
    REFERENCES `proyectosfa`.`serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nc_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `proyectosfa`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nc_vendedor`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `proyectosfa`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`nc_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`nc_detalle` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`nc_detalle` (
  `idnc_detalle` INT NOT NULL,
  `id_inv` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  `cantidad` DECIMAL(11,2) NOT NULL,
  `precio` DECIMAL(11,2) NULL,
  `impuesto` DECIMAL(11,2) NULL,
  `subtotal` DECIMAL(11,2) NULL,
  INDEX `fk_ncd_notacredito_idx` (`idnc_detalle` ASC),
  CONSTRAINT `fk_ncd_notacredito`
    FOREIGN KEY (`idnc_detalle`)
    REFERENCES `proyectosfa`.`nota_credito` (`idnota_credito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`factura` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `codigo_serie` INT NOT NULL,
  `numero_fac` INT NOT NULL,
  `estado` INT NOT NULL,
  `fecha_documento` DATE NULL,
  `fecha_creacion` DATE NULL,
  `cliente_id` INT NOT NULL,
  `vendedor_id` INT NOT NULL,
  `total` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_fact_serie_idx` (`codigo_serie` ASC),
  INDEX `fk_fact_cliente_idx` (`cliente_id` ASC),
  INDEX `fk_fac_vendedor_idx` (`vendedor_id` ASC),
  CONSTRAINT `fk_fact_serie`
    FOREIGN KEY (`codigo_serie`)
    REFERENCES `proyectosfa`.`serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `proyectosfa`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fac_vendedor`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `proyectosfa`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`fac_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`fac_detalle` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`fac_detalle` (
  `idfac_detalle` INT NOT NULL AUTO_INCREMENT,
  `idfactura` INT NOT NULL,
  `id_inv` INT NOT NULL,
  `id_almacen` INT NOT NULL,
  `cantidad` DECIMAL(11,2) NULL,
  `precio` DECIMAL(11,2) NULL,
  `impuesto` DECIMAL(11,2) NULL,
  `subtotal` DECIMAL(11,2) NULL,
  INDEX `fk_fcdetalle_factura_idx` (`idfactura` ASC),
  PRIMARY KEY (`idfac_detalle`),
  CONSTRAINT `fk_fcdetalle_factura`
    FOREIGN KEY (`idfactura`)
    REFERENCES `proyectosfa`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`pago_recibido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`pago_recibido` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`pago_recibido` (
  `idpago_recibido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_fcaja` INT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idpago_recibido`),
  INDEX `fk_pr_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_pr_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `proyectosfa`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`pago_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`pago_detalle` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`pago_detalle` (
  `idpago_detalle` INT NOT NULL,
  `id_factura` INT NOT NULL,
  `saldo` DECIMAL(11,2) NULL,
  INDEX `fk_pd_pr_idx` (`idpago_detalle` ASC),
  INDEX `fk_pd_factura_idx` (`id_factura` ASC),
  CONSTRAINT `fk_pd_pr`
    FOREIGN KEY (`idpago_detalle`)
    REFERENCES `proyectosfa`.`pago_recibido` (`idpago_recibido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pd_factura`
    FOREIGN KEY (`id_factura`)
    REFERENCES `proyectosfa`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`combustible`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`combustible` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`combustible` (
  `idcombustible` INT NOT NULL AUTO_INCREMENT,
  `combustible` VARCHAR(50) NULL,
  PRIMARY KEY (`idcombustible`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`marca` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nombreMarca` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(75) NULL,
  `status` INT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`color` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`color` (
  `idcolor` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcolor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`estado` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`tipo_reparacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`tipo_reparacion` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`tipo_reparacion` (
  `idtipo_reparacion` INT NOT NULL AUTO_INCREMENT,
  `tipo_reparacioncol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipo_reparacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`reparacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`reparacion` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`reparacion` (
  `idreparacion` INT NOT NULL AUTO_INCREMENT,
  `idtipo_reparacion` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `costo` DOUBLE NULL,
  PRIMARY KEY (`idreparacion`),
  INDEX `fk_reparacion_tipo_idx` (`idtipo_reparacion` ASC),
  CONSTRAINT `fk_reparacion_tipo`
    FOREIGN KEY (`idtipo_reparacion`)
    REFERENCES `proyectosfa`.`tipo_reparacion` (`idtipo_reparacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`vehiculo` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`vehiculo` (
  `idvehiculo` INT NOT NULL AUTO_INCREMENT,
  `idmarca` INT NOT NULL,
  `costo` DOUBLE NULL,
  `precio` DOUBLE NULL,
  `numpuertas` INT NULL,
  `idcombustible` INT NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `idcolor` INT NOT NULL,
  `modelo` VARCHAR(50) NULL,
  `estado` INT NOT NULL,
  `idreparacion` INT NULL,
  `tipomoto` VARCHAR(40) NULL,
  PRIMARY KEY (`idvehiculo`),
  INDEX `fk_vehiculo_combustible_idx` (`idcombustible` ASC),
  INDEX `fk_vehiculo_marca_idx` (`idmarca` ASC),
  INDEX `fk_vehiculo_color_idx` (`idcolor` ASC),
  INDEX `fk_vehiculo_color_idx1` (`estado` ASC),
  INDEX `fk_vehiculo_reparacion_idx` (`idreparacion` ASC),
  CONSTRAINT `fk_vehiculo_combustible`
    FOREIGN KEY (`idcombustible`)
    REFERENCES `proyectosfa`.`combustible` (`idcombustible`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_marca`
    FOREIGN KEY (`idmarca`)
    REFERENCES `proyectosfa`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_color`
    FOREIGN KEY (`idcolor`)
    REFERENCES `proyectosfa`.`color` (`idcolor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `proyectosfa`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_reparacion`
    FOREIGN KEY (`idreparacion`)
    REFERENCES `proyectosfa`.`reparacion` (`idreparacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`modelo` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`modelo` (
  `idmodelo` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(50) NULL,
  PRIMARY KEY (`idmodelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`reparacion_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`reparacion_detalle` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`reparacion_detalle` (
  `idreparacion_detalle` INT NOT NULL,
  `idreparacion` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NULL,
  `costo` DOUBLE NULL,
  PRIMARY KEY (`idreparacion_detalle`),
  CONSTRAINT `fk_detalle_reparacion`
    FOREIGN KEY (`idreparacion`)
    REFERENCES `proyectosfa`.`reparacion` (`idreparacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`repuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`repuesto` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`repuesto` (
  `idrepuesto` INT NOT NULL,
  `tipo` INT NULL,
  `descripcion` VARCHAR(50) NULL,
  `estado` INT NULL,
  `idtipo_reparacion` INT NOT NULL,
  `existencias` INT NULL,
  PRIMARY KEY (`idrepuesto`),
  INDEX `fk_repuesto_tiporeparacion_idx` (`idtipo_reparacion` ASC),
  CONSTRAINT `fk_repuesto_tiporeparacion`
    FOREIGN KEY (`idtipo_reparacion`)
    REFERENCES `proyectosfa`.`tipo_reparacion` (`idtipo_reparacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`tipoprov`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`tipoprov` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`tipoprov` (
  `idtipoprov` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idtipoprov`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NULL,
  `nombre` VARCHAR(250) NOT NULL,
  `direccion` VARCHAR(250) NULL,
  `ciudad` VARCHAR(50) NULL,
  `telefono` VARCHAR(50) NULL,
  `nit` VARCHAR(50) NULL,
  `correo` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `idtipo` INT NOT NULL,
  PRIMARY KEY (`idproveedor`),
  INDEX `fk_proveedor_tipo_idx` (`idtipo` ASC),
  CONSTRAINT `fk_proveedor_tipo`
    FOREIGN KEY (`idtipo`)
    REFERENCES `proyectosfa`.`tipoprov` (`idtipoprov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`facturarepuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`facturarepuesto` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`facturarepuesto` (
  `idfacturarepuesto` INT NOT NULL AUTO_INCREMENT,
  `nodoc` VARCHAR(55) NULL,
  `fechacompra` DATE NULL,
  `estado` INT NULL,
  `idproveedor` INT NOT NULL,
  PRIMARY KEY (`idfacturarepuesto`),
  INDEX `fk_facrepuesto_proveedor_idx` (`idproveedor` ASC),
  CONSTRAINT `fk_facrepuesto_proveedor`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `proyectosfa`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectosfa`.`detallefacrepuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectosfa`.`detallefacrepuesto` ;

CREATE TABLE IF NOT EXISTS `proyectosfa`.`detallefacrepuesto` (
  `iddetalle` INT NOT NULL AUTO_INCREMENT,
  `idfacturarepuesto` INT NOT NULL,
  `idrepuesto` INT NULL,
  `cantidad` INT NULL,
  `descripcion` VARCHAR(75) NULL,
  `costo` DOUBLE NULL,
  PRIMARY KEY (`iddetalle`),
  INDEX `fk_dt_ftrepuesto_idx` (`idfacturarepuesto` ASC),
  INDEX `fk_dt_repuesto_idx` (`idrepuesto` ASC),
  CONSTRAINT `fk_dt_ftrepuesto`
    FOREIGN KEY (`idfacturarepuesto`)
    REFERENCES `proyectosfa`.`facturarepuesto` (`idfacturarepuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dt_repuesto`
    FOREIGN KEY (`idrepuesto`)
    REFERENCES `proyectosfa`.`repuesto` (`idrepuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `proyectosfa`.`combustible`
-- -----------------------------------------------------
START TRANSACTION;
USE `proyectosfa`;
INSERT INTO `proyectosfa`.`combustible` (`idcombustible`, `combustible`) VALUES (1, 'Diesel');
INSERT INTO `proyectosfa`.`combustible` (`idcombustible`, `combustible`) VALUES (2, 'Gasolina');

COMMIT;


-- -----------------------------------------------------
-- Data for table `proyectosfa`.`color`
-- -----------------------------------------------------
START TRANSACTION;
USE `proyectosfa`;
INSERT INTO `proyectosfa`.`color` (`idcolor`, `color`) VALUES (1, 'Rojo');
INSERT INTO `proyectosfa`.`color` (`idcolor`, `color`) VALUES (2, 'Azul');
INSERT INTO `proyectosfa`.`color` (`idcolor`, `color`) VALUES (3, 'Blanco');
INSERT INTO `proyectosfa`.`color` (`idcolor`, `color`) VALUES (4, 'Verde');
INSERT INTO `proyectosfa`.`color` (`idcolor`, `color`) VALUES (5, 'Negro');
INSERT INTO `proyectosfa`.`color` (`idcolor`, `color`) VALUES (6, 'Amarillo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `proyectosfa`.`tipoprov`
-- -----------------------------------------------------
START TRANSACTION;
USE `proyectosfa`;
INSERT INTO `proyectosfa`.`tipoprov` (`idtipoprov`, `descripcion`) VALUES (1, 'Local');
INSERT INTO `proyectosfa`.`tipoprov` (`idtipoprov`, `descripcion`) VALUES (2, 'Importaciones');

COMMIT;

